version: "2.4"
services:
  pipe_elasticsearch:
    env_file: .env
    build: .
    volumes:
      - ./dist:/home/x/src/dist
      - ./isx-pipe-elasticsearch.cabal:/home/x/src/isx-pipe-elasticsearch.cabal
      - ./lib:/home/x/src/lib
      - ./src:/home/x/src/src
      - ./test:/home/x/src/test
    networks:
      plugin:
        aliases:
          - elasticsearch.plugins.isoxya-stag.pavouk.tech
      test: {}
  elasticsearch:
    image: docker.io/library/elasticsearch:7.6.2
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - plugin
  kibana:
    image: docker.io/library/kibana:7.6.2
    networks:
      - plugin
  test_echo:
    image: docker.io/keisato/http-echo:latest
    networks:
      - test
volumes:
  elasticsearch: {}
networks:
  plugin:
    external: true
    name: isx_plugin
  test: {}
