version: "2.4"
services:
  plugin_elasticsearch:
    env_file: .env
    build: .
    volumes:
      - ./dist:/home/x/src/dist
      - ./isx-plugin-elasticsearch.cabal:/home/x/src/isx-plugin-elasticsearch.cabal
      - ./lib:/home/x/src/lib
      - ./src:/home/x/src/src
      - ./test:/home/x/src/test
    networks:
      plugin:
        aliases:
          - elasticsearch.plugins.isoxya-stag.pavouk.tech
      test: {}
  elasticsearch:
    env_file: .env
    image: docker.io/library/elasticsearch:7.7.0
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-security.html
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - plugin
  kibana:
    env_file: .env
    image: docker.io/library/kibana:7.7.0
    # https://www.elastic.co/guide/en/kibana/current/using-kibana-with-security.html
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_USERNAME: kibana
      XPACK_SECURITY_ENABLED: "true"
    networks:
      - plugin
  test_echo:
    image: docker.io/keisato/http-echo:latest
    networks:
      - test
volumes:
  elasticsearch: {}
networks:
  plugin:
    external: true
    name: isx_plugin
  test: {}
