version: "2.4"
services:
  plug_elasticsearch:
    image: docker.package.tiredpixel.com/isoxya/isoxya-plugin-elasticsearch-build:head
    volumes:
      - ./lib:/home/x/repo/lib
      - ./src:/home/x/repo/src
      - ./test:/home/x/repo/test
      #
      - ./isx-plug-elasticsearch.cabal:/home/x/repo/isx-plug-elasticsearch.cabal
    networks:
      es: {}
      plug:
        aliases:
          - elasticsearch.plugin.dev.isoxya.com
      test: {}
  test_echo:
    image: docker.io/keisato/http-echo:latest
    networks:
      - test
networks:
  es:
    external: true
    name: isoxya_es
  plug:
    external: true
    name: isoxya_plug
  test: {}
