version: "2.4"
services:
  pipe_elasticsearch:
    env_file: .env
    build: .
    volumes:
      - ./isx-pipe-elasticsearch.cabal:/home/x/src/isx-pipe-elasticsearch.cabal
      - ./lib:/home/x/src/lib
      - ./src:/home/x/src/src
      - ./test:/home/x/src/test
    networks:
      pipe:
        aliases:
          - elasticsearch.pipe.proc.isoxya.pavouk.tech
      db: {}
  web:
    env_file: .env
    image: kibana:7.3.1
    networks:
      - web
      - db
  db:
    image: elasticsearch:7.3.1
    environment:
      discovery.type: single-node
    volumes:
      - db:/usr/share/elasticsearch/data
    networks:
      - db
volumes:
  db: {}
networks:
  db: {}
  web: {}
  pipe:
    external: true
    name: isx_pipe
