version: "2.4"
services:
  plugin_elasticsearch:
    env_file: .env
    image: registry.packages.tiredpixel.com/base/isoxya-plugin-elasticsearch-build:head
    networks:
      plugin:
        aliases:
          - elasticsearch.plugins.dev.isoxya.com
      test: {}
  es:
    env_file: .env
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-security.html
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
    image: docker.io/library/elasticsearch:7.8.0
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - plugin
  kib:
    env_file: .env
    # https://www.elastic.co/guide/en/kibana/current/using-kibana-with-security.html
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_USERNAME: kibana
      XPACK_SECURITY_ENABLED: "true"
    image: docker.io/library/kibana:7.8.0
    networks:
      - plugin
  test_echo:
    image: docker.io/keisato/http-echo:latest
    networks:
      - test
volumes:
  es: {}
networks:
  plugin:
    external: true
    name: isoxya_plugin
  test: {}
